import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { LoginComponent } from '@src/app/login/login.component';
import { CreateFamilyAccountComponent } from '@src/app/create-family-account/create-family-account.component';
import { FamilyComponent } from '@src/app/family/family.component';
import { CreateMemberComponent } from '@src/app/create-member/create-member.component';


export const routes: Routes = [
  {
      path: 'auto',
      redirectTo: '/auto-generated',
      pathMatch: 'full',
  },
  {
      path: 'auto-generated',
      component: AutoGeneratedComponent,
  },
  { path: '', component: LoginComponent},
  { path: 'create', component: CreateFamilyAccountComponent},
  { path: 'family', component: FamilyComponent},
  { path: 'addMember', component: CreateMemberComponent}
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
