import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { CreateFamilyAccountComponent } from '@src/app/create-family-account/create-family-account.component';
import { CreateMemberComponent } from '@src/app/create-member/create-member.component';
import { FamilyComponent } from '@src/app/family/family.component';
import { LoginComponent } from '@src/app/login/login.component';


// Uncomment and add to NgModule imports if you need to use two-way binding
 import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
 import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';
import { DashboardComponent } from '@src/app/dashboard/dashboard.component';
import { WelcomeComponent } from '@src/app/dashboard/welcome/welcome.component';
import { ConsultationComponent } from '@src/app/dashboard/consultation/consultation.component';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    CreateFamilyAccountComponent,
    CreateMemberComponent,
    FamilyComponent,
    LoginComponent,
    DashboardComponent,
    WelcomeComponent,
    ConsultationComponent,
  ],
  imports: [
    NativeScriptModule,
    NativeScriptFormsModule,
    NativeScriptHttpClientModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
