import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { CreateMemberComponent } from '@src/app/create-member/create-member.component';
import { CreateFamilyAccountComponent } from '@src/app/create-family-account/create-family-account.component';
import { FamilyComponent } from '@src/app/family/family.component';
import { LoginComponent } from '@src/app/login/login.component';
import { MaterialModule } from '@src/core/material.module';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { HttpClientModule } from '@angular/common/http';
import { DashboardComponent } from '@src/app/dashboard/dashboard.component';
import { WelcomeComponent } from '@src/app/dashboard/welcome/welcome.component';
import { ConsultationComponent } from '@src/app/dashboard/consultation/consultation.component';

@NgModule({
  declarations: [
    AppComponent,
    CreateMemberComponent,
    CreateFamilyAccountComponent,
    FamilyComponent,
    LoginComponent,
    AutoGeneratedComponent,
    DashboardComponent,
    WelcomeComponent,
    ConsultationComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    MaterialModule,
    ReactiveFormsModule,
    FormsModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
